#!/bin/sh

file=$1

~/opt/retdec/bin/retdec-decompiler -k "${file}"
mv -v "${file}.c" "${file}_decomp_retdec.c"
rm -v "${file}."*{ll,json,dsm,bc}
objdump -t -T -x -D -s -r -R -s "${file}" > "${file}_objdump.txt"
readelf -a "${file}" > "${file}_readelf.txt"
